import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import { Container, Box, BottomNavigation } from "@mui/material";
import * as React from "react";
import BottomNav from "./components/Common/BottomNav";
import UserProvider from "./context/UserProvider";

const inter = Inter({ subsets: ["latin"] });
// const roboto = Roboto({ subsets: ["latin"] });

export const metadata = {
  title: "Insight",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Container
          className="phone-container"
          maxWidth="xs"
          sx={{ backgroundColor: "#F6F7FC" }}
        >
          <Container maxWidth="lg" disableGutters className="children">
            <UserProvider>{children}</UserProvider>
          </Container>
          <BottomNav />
        </Container>
      </body>
    </html>
  );
}
